const fallbackBenefits = [
  { name: "Samsung", cashbackMessage: "4,5% de saldo" },
  { name: "Shein", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Primor", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Dyson", cashbackMessage: "4,5% de saldo" },
  { name: "Temu", cashbackMessage: "Hasta 5% de saldo" },
  { name: "MediaMarkt", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Vayacruceros.com", cashbackMessage: "2% de saldo" },
  { name: "Barceló Hotels & Resorts", cashbackMessage: "5% de saldo" },
  { name: "Miravia", cashbackMessage: "5% de saldo" },
  { name: "AliExpress", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Hoteles.com", cashbackMessage: "4,5% de saldo" },
  { name: "PcComponentes", cashbackMessage: "Hasta 4,5% de saldo" },
  { name: "Decathlon", cashbackMessage: "Hasta 5,5% de saldo" },
  { name: "LG", cashbackMessage: "3,5% de saldo" },
  { name: "HSN", cashbackMessage: "4,5% de saldo" },
  { name: "Adidas", cashbackMessage: "Hasta 7,5% de saldo" },
  { name: "Nike", cashbackMessage: "Hasta 3% de saldo" },
  { name: "El Corte Inglés", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Game", cashbackMessage: "Hasta 5% de saldo" },
  { name: "H&M", cashbackMessage: "Hasta 4,5% de saldo" },
  { name: "IKEA", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Amazon", cashbackMessage: "Hasta 1% de saldo" },
  { name: "Huawei", cashbackMessage: "4% de saldo" },
  { name: "Sierra Nevada", cashbackMessage: "2% de saldo" },
  { name: "Primark", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Fnac", cashbackMessage: "3,5% de saldo" },
  { name: "Atrápalo", cashbackMessage: "Hasta 7% de saldo" },
  { name: "Padel Nuestro", cashbackMessage: "1% de saldo" },
  { name: "Just Eat", cashbackMessage: "3% de saldo" },
  { name: "Zalando", cashbackMessage: "Hasta 6% de saldo" },
  { name: "Europcar", cashbackMessage: "5,5% de saldo" },
  { name: "Lastminute.com", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Myprotein", cashbackMessage: "5% de saldo" },
  { name: "eDreams", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Rumbo", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Vinoselección", cashbackMessage: "2% de saldo" },
  { name: "GOLDCAR", cashbackMessage: "5,5% de saldo" },
  { name: "Worten", cashbackMessage: "3,5% de saldo" },
  { name: "Atida Mifarma", cashbackMessage: "5% de saldo" },
  { name: "Weekendesk", cashbackMessage: "5,5% de saldo" },
  { name: "Nintendo", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Rituals", cashbackMessage: "Hasta 6% de saldo" },
  { name: "Druni", cashbackMessage: "3,5% de saldo" },
  { name: "Google Play", cashbackMessage: "Hasta 3% de saldo" },
  { name: "TheFork", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Xbox", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Fever", cashbackMessage: "Hasta 4% de saldo" },
  { name: "CECOTEC", cashbackMessage: "5% de saldo" },
  { name: "Tiendanimal", cashbackMessage: "6% de saldo" },
  { name: "Sony Playstation Store", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Casa del Libro", cashbackMessage: "Hasta 7% de saldo" },
  { name: "Promofarma", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Burger King", cashbackMessage: "1,5% de saldo" },
  { name: "Cinesa", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Ticketmaster", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Glovo", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Wible", cashbackMessage: "Hasta 1,5% de saldo" },
  { name: "Entradas.com", cashbackMessage: "Hasta 1,5% de saldo" },
  { name: "GetYourGuide", cashbackMessage: "3,5% de saldo" },
  { name: "Conforama", cashbackMessage: "3% de saldo" },
  { name: "Airbnb", cashbackMessage: "Hasta 2% de saldo" },
  { name: "Cine", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Kiwoko", cashbackMessage: "3% de saldo" },
  { name: "Brico Depôt", cashbackMessage: "3,5% de saldo" },
  { name: "Amazon Electrónica", cashbackMessage: "7% de saldo" },
  { name: "Forum", cashbackMessage: "3,5% de saldo" },
  { name: "JDSPORTS", cashbackMessage: "3% de saldo" },
  { name: "Lefties", cashbackMessage: "3% de saldo" },
  { name: "Privé by Zalando", cashbackMessage: "3% de saldo" },
  { name: "Pandora", cashbackMessage: "4,5% de saldo" },
  { name: "Pikolin", cashbackMessage: "6% de saldo" },
  { name: "Freshly Cosmetics", cashbackMessage: "8% de saldo" },
  { name: "HP Store", cashbackMessage: "1,5% de saldo" },
  { name: "NH Hoteles", cashbackMessage: "4,5% de saldo" },
  { name: "Iberostar", cashbackMessage: "4,5% de saldo" },
  { name: "Uniqlo", cashbackMessage: "6% de saldo" },
  { name: "Douglas", cashbackMessage: "5,5% de saldo" },
  { name: "Desigual", cashbackMessage: "6% de saldo" },
  { name: "Sephora", cashbackMessage: "6% de saldo" },
  { name: "vidaXL", cashbackMessage: "6% de saldo" },
  { name: "Bershka", cashbackMessage: "4% de saldo" },
  { name: "Dosfarma", cashbackMessage: "4% de saldo" },
  { name: "Intermundial", cashbackMessage: "7% de saldo" },
  { name: "Sprinter", cashbackMessage: "5% de saldo" },
  { name: "Apple", cashbackMessage: "Hasta 1% de saldo" },
  { name: "Agoda", cashbackMessage: "4% de saldo" },
  { name: "Clarins", cashbackMessage: "6% de saldo" },
  { name: "Expedia", cashbackMessage: "2,5% de saldo" },
  { name: "Renfe", cashbackMessage: "10% de descuento" },
  { name: "Norauto", cashbackMessage: "Hasta 30% dto." },
  { name: "Lavados Repsol", cashbackMessage: "Compra lavados" },
  { name: "Spotify", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Uber / Uber Eats", cashbackMessage: "Hasta 2% de saldo" }
];

export { fallbackBenefits };
