const fallbackBenefits = [
  { name: "Samsung", cashbackMessage: "4,5% de saldo" },
  { name: "Shein ", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Primor", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Dyson", cashbackMessage: "4,5% de saldo" },
  { name: "Temu", cashbackMessage: "Hasta 5% de saldo" },
  { name: "MediaMarkt", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Vayacruceros.com", cashbackMessage: " 2% de saldo" },
  { name: "Barceló Hotels & Resorts", cashbackMessage: "5% de saldo" },
  { name: "Miravia", cashbackMessage: "5% de saldo" },
  { name: "AliExpress", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Hoteles.com", cashbackMessage: "4,5% de saldo" },
  { name: "PcComponentes", cashbackMessage: "Hasta 4,5% de saldo" },
  { name: "Decathlon", cashbackMessage: "Hasta 5,5% de saldo" },
  { name: "LG", cashbackMessage: "3,5% de saldo" },
  { name: "HSN", cashbackMessage: "4,5% de saldo" },
  { name: "Adidas", cashbackMessage: "Hasta 7,5% de saldo" },
  { name: "Nike", cashbackMessage: "Hasta 3% de saldo" },
  { name: "El Corte Inglés", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Game", cashbackMessage: "Hasta 5% de saldo" },
  { name: "H&M", cashbackMessage: "Hasta 4,5% de saldo" },
  { name: "IKEA", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Amazon", cashbackMessage: "Hasta 1% de saldo" },
  { name: "Huawei", cashbackMessage: "4% de saldo" },
  { name: "Sierra Nevada", cashbackMessage: "2% de saldo" },
  { name: "Primark", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Fnac", cashbackMessage: "3,5% de saldo" },
  { name: "Atrápalo", cashbackMessage: "Hasta 7% de saldo" },
  { name: "Padel Nuestro", cashbackMessage: "1% de saldo" },
  { name: "Just Eat", cashbackMessage: "3% de saldo" },
  { name: "Zalando", cashbackMessage: "Hasta 6% de saldo" },
  { name: "Europcar", cashbackMessage: "5,5% de saldo" },
  { name: "Lastminute.com", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Myprotein", cashbackMessage: "5% de saldo" },
  { name: "eDreams", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Rumbo", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Vinoselección", cashbackMessage: " 2% de saldo" },
  { name: "GOLDCAR", cashbackMessage: "5,5% de saldo" },
  { name: "Worten", cashbackMessage: "3,5% de saldo" },
  { name: "Atida Mifarma", cashbackMessage: "5% de saldo" },
  { name: "Weekendesk", cashbackMessage: "5,5% de saldo" },
  { name: "Nintendo", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Rituals", cashbackMessage: "Hasta 6% de saldo" },
  { name: "Druni", cashbackMessage: "3,5% de saldo" },
  { name: "Google Play", cashbackMessage: "Hasta 3% de saldo" },
  { name: "TheFork", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Xbox", cashbackMessage: "Hasta 5% de saldo" },
  { name: "Fever", cashbackMessage: "Hasta 4% de saldo" },
  { name: "CECOTEC", cashbackMessage: "5% de saldo" },
  { name: "Tiendanimal", cashbackMessage: "6% de saldo" },
  { name: "Sony Playstation Store", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Casa del Libro", cashbackMessage: "Hasta 7% de saldo" },
  { name: "Promofarma", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Burger King", cashbackMessage: " 1,5% de saldo" },
  { name: "Cinesa", cashbackMessage: "Hasta 4% de saldo" },
  { name: "Ticketmaster", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Glovo", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "Wible", cashbackMessage: "Hasta 1,5% de saldo" },
  { name: "Entradas.com", cashbackMessage: "Hasta 1,5% de saldo" },
  { name: "GetYourGuide", cashbackMessage: "3,5% de saldo" },
  { name: "Conforama", cashbackMessage: "3% de saldo" },
  { name: "Airbnb", cashbackMessage: "Hasta 2% de saldo" },
  { name: "Cine", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Kiwoko", cashbackMessage: "3% de saldo" },
  { name: "Brico Depôt", cashbackMessage: "3,5% de saldo" },
  { name: "Amazon Electrónica", cashbackMessage: " 7% de saldo " },
  { name: "Forum", cashbackMessage: "3,5% de saldo" },
  { name: "JDSPORTS", cashbackMessage: "3% de saldo" },
  { name: "Lefties", cashbackMessage: "3% de saldo" },
  { name: "Privé by Zalando", cashbackMessage: "3% de saldo" },
  { name: "Pandora", cashbackMessage: "4,5% de saldo" },
  { name: "Pikolin", cashbackMessage: "6% de saldo" },
  { name: "Freshly Cosmetics", cashbackMessage: "8% de saldo" },
  { name: "HP Store", cashbackMessage: "1,5% de saldo" },
  { name: "NH Hoteles", cashbackMessage: "4,5% de saldo" },
  { name: "Iberostar", cashbackMessage: "4,5% de saldo" },
  { name: "Uniqlo", cashbackMessage: "6% de saldo" },
  { name: "Douglas", cashbackMessage: "5,5% de saldo" },
  { name: "Desigual", cashbackMessage: "6% de saldo" },
  { name: "Sephora", cashbackMessage: "6% de saldo" },
  { name: "vidaXL", cashbackMessage: "6% de saldo" },
  { name: "Bershka", cashbackMessage: "4% de saldo" },
  { name: "Dosfarma", cashbackMessage: "4% de saldo" },
  { name: "Intermundial", cashbackMessage: "7% de saldo" },
  { name: "Sprinter", cashbackMessage: "5% de saldo" },
  { name: "Apple", cashbackMessage: "Hasta 1% de saldo" },
  { name: "Agoda", cashbackMessage: "4% de saldo" },
  { name: "Clarins", cashbackMessage: "6% de saldo" },
  { name: "Expedia", cashbackMessage: "2,5% de saldo" },
  { name: "Renfe", cashbackMessage: "10% de descuento" },
  { name: "Norauto", cashbackMessage: "Hasta 30% dto." },
  { name: "Wicked, el musical", cashbackMessage: "2% de saldo" },
  { name: "Los Miserables, el musical", cashbackMessage: "2% de saldo" },
  { name: "Lavados Repsol", cashbackMessage: "Compra lavados" },
  { name: "The Book of Mormon", cashbackMessage: "2% de saldo" },
  { name: "Bono Parques", cashbackMessage: "3% de saldo" },
  { name: "Motor Verde ", cashbackMessage: "2% de saldo" },
  { name: "Emma", cashbackMessage: "4,5% de saldo" },
  { name: "Destinia", cashbackMessage: "Hasta 4,5% de saldo" },
  { name: "Bilbao BBK Live 2026", cashbackMessage: "2% de saldo" },
  { name: "Spotify ", cashbackMessage: "Hasta 3% de saldo" },
  { name: "Trasmed", cashbackMessage: "10% de saldo" },
  { name: "Uber / Uber Eats", cashbackMessage: "Hasta 2% de saldo" },
  { name: "Zooplus", cashbackMessage: "Hasta 2,5% de saldo" },
  { name: "Enterticket", cashbackMessage: "2% de saldo" },
  { name: "Zoo Aquarium Madrid", cashbackMessage: "3% de saldo" },
  { name: "Parque Warner", cashbackMessage: "3% de saldo" },
  { name: "Parque de Atracciones de Madrid", cashbackMessage: "3% de saldo" },
  { name: "Popeyes", cashbackMessage: "1,5% de saldo" },
  { name: "Quehoteles.com", cashbackMessage: "1,5% de saldo" },
  { name: "Faunia", cashbackMessage: "3% de saldo" },
  { name: "Atlantis Aquarium", cashbackMessage: "3% de saldo" },
  { name: "Clickferry", cashbackMessage: "2% de saldo" },
  { name: "Tienda Online Repsol", cashbackMessage: "5% de saldo" },
  { name: "Ruralka", cashbackMessage: "5% de saldo" },
  { name: "SaludOnNet", cashbackMessage: "Hasta 3,5% de saldo" },
  { name: "I love Reggaeton Sevilla", cashbackMessage: " 2% de saldo" },
  { name: "Monegros", cashbackMessage: "2% de saldo" },
  { name: "HomyHub", cashbackMessage: "2% de saldo" },
  { name: "FIB", cashbackMessage: "2% de saldo" },
  { name: "LeonLeds", cashbackMessage: "4% de saldo" },
  { name: "Granada Sound", cashbackMessage: "2% de saldo" },
  { name: "I love Reggaeton Valencia", cashbackMessage: "2% de saldo" },
  { name: "Arenal Sound", cashbackMessage: "2% de saldo" },
  { name: "Sonórica", cashbackMessage: "2% de saldo" },
  { name: "Resurrection Fest", cashbackMessage: "2% de saldo" },
  { name: "Sónar", cashbackMessage: " 2% de saldo" },
  { name: "Caudal Fest", cashbackMessage: " 2% de saldo" },
  { name: "Interestelar Sevilla", cashbackMessage: " 2% de saldo" },
  { name: "Festival de Les Arts", cashbackMessage: " 2% de saldo" },
  { name: "Elrow XXL Murcia", cashbackMessage: " 2% de saldo" },
  { name: "Love The Twenties Barcelona", cashbackMessage: "2% de saldo" },
  { name: "Love the 90s Gijón", cashbackMessage: " 2% de saldo" },
  { name: "Marenostrum Fuengirola", cashbackMessage: "2% de saldo" },
  { name: "Elrow XXL Sevilla", cashbackMessage: "2% de saldo" },
  { name: "Tarracoarena", cashbackMessage: "2% de saldo" },
  { name: "Elrow town Madrid", cashbackMessage: "2% de saldo" },
  { name: "Santander Music", cashbackMessage: " 2% de saldo" },
  { name: "El Economista", cashbackMessage: "10% de saldo" },
  { name: "Love the 90s Valencia", cashbackMessage: "2% de saldo" },
  { name: "Love the 90s Barcelona", cashbackMessage: " 2% de saldo" },
  { name: "Nostalgia Milenial Barcelona", cashbackMessage: "2% de saldo" },
  { name: "Nostalgia Milenial Sevilla", cashbackMessage: "2% de saldo" },
  { name: "I love Reggaeton Barcelona", cashbackMessage: " 2% de saldo" },
  { name: "Nostalgia Milenial Madrid", cashbackMessage: "2% de saldo" },
  { name: "Love The Twenties Madrid", cashbackMessage: "2% de saldo" },
  { name: "Nostalgia Milenial Alicante", cashbackMessage: "2% de saldo" },
  { name: "Love the 90s Madrid", cashbackMessage: "2% de saldo" },
  { name: "Love the 90s Alicante", cashbackMessage: "2% de saldo" },
  { name: "I love Reggaeton Madrid", cashbackMessage: "2% de saldo" },
  { name: "I love Reggaeton Gijón", cashbackMessage: "2% de saldo" },
  { name: "Love the 90s Córdoba", cashbackMessage: "2% de saldo" }
];

export { fallbackBenefits };
